version: '3.9'

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-application
    ports:
      - 8000:8000
    volumes:
    - .:/app/
    command: sh entrypoint.sh
    env_file:
     - .env
    depends_on:
     - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - 5432:5432
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
     - .env

  redis: 
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - django-app
    command: celery -A core.project worker --loglevel=info
    volumes:
      - .:/app/

  celery-beat:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - django-app
    command: celery -A core.project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app/

volumes:
  postgres_data_volume: