# Generated by Django 5.0.3 on 2024-03-26 18:18

import core.apps.delivery.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Название города')),
                ('state', models.CharField(max_length=255, verbose_name='Название штата')),
                ('zip_code', models.CharField(verbose_name='Почтовый индекс (zip)')),
                ('latitude', models.FloatField(validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)], verbose_name='Широта')),
                ('longitude', models.FloatField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)], verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='DeliveryCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{4}[A-Z]$')], verbose_name='Уникальный номер')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Грузоподъемность')),
                ('current_location', models.ForeignKey(default=core.apps.delivery.models.Location.get_random_location, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='delivery.location', verbose_name='Текущая локация')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Вес груза')),
                ('description', models.TextField(verbose_name='Описание груза')),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='delivery.location', verbose_name='Локация доставки')),
                ('pick_up_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_ups', to='delivery.location', verbose_name='Локация подбора')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
    ]
